version: "3.6"

services:
  client:
    stdin_open: true
    container_name: react-client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    container_name: go-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: pg-db
    restart: always
    environment: 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: