version: "3.6"

services:
  client:
    stdin_open: true
    build: 
      context: ./client
    env_file:
      - ./client/docker.env
    ports:
      - 3000:3000

  api:
    build:
      context: ./server
    env_file:
      - ./data/redis/docker.env
      - ./data/postgres/docker.env
      - ./server/docker.env
    ports:
      - 8000:8000

  cache:
    image: redis:latest
    env_file:
      - ./data/redis/docker.env
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis

  db:
    image: postgres:latest
    env_file:
      - ./data/postgres/docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  redis-data:
  postgres-data:
