version: "3.6"

services:
  client:
    stdin_open: true
    build: 
      context: ./client
    env_file:
      - ./client/docker.env
    ports:
      - 3000:3000

  api:
    build:
      context: ./server
    environment:
      - GO_ENV=docker-dev
    env_file:
      - ./data/redis/docker.env
      - ./data/postgres/docker.env
      - ./server/docker.env
    depends_on:
      - db
      - cache
    ports:
      - 8000:8000
      
  cache:
    image: redis:latest
    env_file:
      - ./data/redis/docker.env
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - 8081:8081

  db:
    image: postgres:latest
    env_file:
      - ./data/postgres/docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  postgres_data:
  redis_data: