version: "3.6"

services:
  client:
    stdin_open: true
    build: 
      context: ./client
    env_file:
      - ./client/docker.env
    ports:
      - 3000:3000

  api:
    build:
      context: ./server
    env_file:
      - ./pgdata/docker.env
      - ./server/docker.env
    ports:
      - 8000:8000

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./pgdata/docker.env
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080